### ISSUE TITLE
Does `reset` method have the same effect as setting coeff to 0?

### ISSUE THREAD

**Issue by trung6** [vgel/repeng#50]
Hi, thanks for your greater work!

I just wonder if calling `model.reset()` would be the same as calling `model.set_control(control_vector, coeff=0)`?

**Comment by vgel** [comment]
`model.reset()` is the same as calling `model.set_control(None)`--it actually clears the vectors completely from the model. it's better to use `reset()` before training a new vector, and inference with a reset model is slightly faster, but otherwise the behavior should be identical to using a zeroed vector.
